# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4c6ed38d45ca44ce3506836adfb42fef0551b8863cc227f454d5a9a7e758f01b722e3ebd7da6f8b38878d1410a9bdaf803e1031c71aeb39703218850b50896

test:
  secret_key_base: 914417e1dc7c499816f92effc2cba0a08bfa61ede4f6c27e595dfd59c7f11c1fe607080d3c58b9a196d32b22485420fbf8fa6908d713167dd3f959f3d4e241b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
